////////////////////////////////////////

const MEDIA = {
    IMAGE: 'I',
    VIDEO: 'V',
    AUDIO: 'A',
    IMAGE_DEFAULT: 'ID',
    IMAGE_WALLPAPER: 'IW',
    VIDEO_FILE: 'VF',
    VIDEO_YOUTUBE: 'VY',
    AUDIO_FILE: 'AF',
}

const MEDIA_REQUEST = {
    IMAGE: MEDIA.IMAGE,
    VIDEO: MEDIA.VIDEO,
    AUDIO: MEDIA.AUDIO,
    IMAGE_DEFAULT: MEDIA.IMAGE_DEFAULT,
    IMAGE_WALLPAPER: MEDIA.IMAGE_WALLPAPER,
    VIDEO_FILE: MEDIA.VIDEO_FILE,
    VIDEO_YOUTUBE: MEDIA.VIDEO_YOUTUBE,
    AUDIO_FILE: MEDIA.AUDIO_FILE,
}

const MEDIA_RESPONSE = {
    IMAGE_DEFAULT: MEDIA.IMAGE_DEFAULT,
    IMAGE_WALLPAPER: MEDIA.IMAGE_WALLPAPER,
    VIDEO_FILE: MEDIA.VIDEO_FILE,
    VIDEO_YOUTUBE: MEDIA.VIDEO_YOUTUBE,
    AUDIO_FILE: MEDIA.AUDIO_FILE,
}

////////////////////////////////////////

export {
    MEDIA_REQUEST, MEDIA_RESPONSE
}