////////////////////////////////////////
// SCREEN
////////////////////////////////////////

const SCREEN = {
    SPLASH: 'SCREEN/SPLASH',
    LOGIN: 'SCREEN/LOGIN',
    LOGIN_RE: 'SCREEN/LOGIN_RE',
    HOME: 'SCREEN/HOME',
    COMMUNITY: 'SCREEN/COMMUNITY',
    NOTICE: 'SCREEN/NOTICE',
    MEMBERSHIP: 'SCREEN/MEMBERSHIP',
    MORE: 'SCREEN/MORE',
}

const SCREEN_ACTIVITY = {
    COMMENT: 'ACTIVITY/COMMENT',
    ALARM_LIST: 'ACTIVITY/ALARM_LIST',
    // Post
    POST: 'ACTIVITY/POST',
    POST_EVENT: 'ACTIVITY/POST_EVENT',
    POST_INQUIRE: 'ACTIVITY/POST_INQUIRE',
    POST_SUGGEST: 'ACTIVITY/POST_SUGGEST',
    POST_VOTE: 'ACTIVITY/POST_VOTE',
    POST_PUBLIC_BROADCAST: 'ACTIVITY/POST_PUBLIC_BROADCAST',
    // Detail
    // POST_DETAIL: 'ACTIVITY/POST_DETAIL',
    POST_DETAIL2: 'ACTIVITY/POST_DETAIL2', //
    NOTICE_DETAIL: 'ACTIVITY/NOTICE_DETAIL',
    INQUIRE_DETAIL: 'ACTIVITY/INQUIRE_DETAIL',
    SUGGEST_DETAIL: 'ACTIVITY/SUGGEST_DETAIL',
    BANNER_DETAIL: 'ACTIVITY/BANNER_DETAIL',
    EVENT_DETAIL: 'ACTIVITY/EVENT_DETAIL',
    GOODS_DETAIL: 'ACTIVITY/GOODS_DETAIL',
    // Media
    MEDIA_IMAGE: 'ACTIVITY/MEDIA_IMAGE',
    MEDIA_WALLPAPER: 'ACTIVITY/MEDIA_WALLPAPER',
    MEDIA_VIDEO: 'ACTIVITY/MEDIA_VIDEO',
    MEDIA_YOUTUBE: 'ACTIVITY/MEDIA_YOUTUBE',
    MEDIA_AUDIO: 'ACTIVITY/MEDIA_AUDIO',
    // SETTING
    SETTING: 'ACTIVITY/SETTING',
    // MEDIA VIEWER
    MEDIA_VIEWER: 'ACTIVITY/MEDIA_VIEWER',
    IMAGE_VIEWER: 'ACTIVITY/IMAGE_VIEWER',

    //TEST
    TEST_PAGE: 'ACTIVITY/TEST_PAGE',
}

////////////////////////////////////////
// STACK
////////////////////////////////////////

const STACK_LOGIN = {
    LOGIN: 'LOGIN/MAIN',
    JOIN: 'LOGIN/JOIN',
    AUTHENTICATION: 'LOGIN/AUTHENTICATION',
    RESET_PASSWORD: 'LOGIN/RESET_PASSWORD',
    CHANGE_PASSWORD: 'LOGIN/CHANGE_PASSWORD',
}

const STACK_HOME = {
    HOME: 'HOME/MAIN',
    KANGDANIEL: 'HOME/KANGDANIEL',
    KANGDANIEL_MEDIA: 'HOME/KANGDANIEL_MEDIA',
}

const STACK_COMMUNITY = {
    COMMUNITY: 'COMMUNITY/MAIN',
    TAB_TALK_TALK: 'COMMUNITY/TALK_TALK',
    TAB_FROM_DANIEL: 'COMMUNITY/FROM_DANIEL',
    TAB_TO_DANIEL: 'COMMUNITY/TO_DANIEL',
}

const STACK_NOTICE = {
    NOTICE: 'NOTICE/MAIN',
    TAB_NOTICE: 'NOTICE/NOTICE',
    TAB_SCHEDULE: 'NOTICE/SCHEDULE',
    TAB_EVENT: 'NOTICE/EVENT',
    TAB_EVENT_NOTICE: 'NOTICE/EVENT/NOTICE',
    TAB_EVENT_PART: 'NOTICE/EVENT/PART',
    TAB_MEDIA: 'NOTICE/MEDIA',
    TAB_GOODS: 'NOTICE/GOODS',
}

const STACK_MEMBERSHIP = {
    MEMBERSHIP: 'MEMBERSHIP/MAIN',
    TAB_NOTICE: 'MEMBERSHIP/NOTICE',
    TAB_MEDIA: 'MEMBERSHIP/MEDIA',
    TAB_TALK: 'MEMBERSHIP/TALK',
    TAB_EVENT: 'MEMBERSHIP/EVENT',
    TAB_EVENT_NOTICE: 'MEMBERSHIP/EVENT/NOTICE',
    TAB_EVENT_PART: 'MEMBERSHIP/EVENT/PART',
}

const STACK_MORE = {
    MORE: 'MORE/MAIN',
    MY_POST: 'MORE/MY_POST',
    PROFILE: 'MORE/PROFILE',
    // Password
    RESET_PASSWORD: 'MORE/RESET_PASSWORD',
    CHANGE_PASSWORD: 'MORE/CHANGE_PASSWORD',
    // Member
    MEMBERSHIP_GUID: 'MORE/MEMBERSHIP_GUID',
    MEMBERSHIP_INFO: 'MORE/MEMBERSHIP_INFO',
    REGULAR_MEMBER_APPLY: 'MORE/REGULAR_MEMBER_APPLY',
    REQUEST_MEMBER: 'MORE/REQUEST_MEMBER',
    // Service
    SERVICE_CENTER: 'MORE/SERVICE_CENTER',
    FAQ: 'MORE/FAQ',
    INQUIRE: 'MORE/INQUIRE',
    INQUIRE_LIST: 'MORE/INQUIRE_LIST',
    SUGGEST: 'MORE/SUGGEST',
    SUGGEST_LIST: 'MORE/SUGGEST_LIST',
    WITHDRAWAL: 'MORE/WITHDRAWAL',
    // Setting
    SETTING: 'MORE/SETTING',
    TERMS_POLICIES: 'MORE/TERMS_POLICIES',
    VERSION_INFO: 'MORE/VERSION_INFO',
    DOWNLOAD_FILE_MNG: 'MORE/DOWNLOAD_FILE_MNG',
    PRODUCT_CERTIFICATION_LIST: 'MORE/PRODUCT_CERTIFICATION_LIST',

}

////////////////////////////////////////
// TAB
////////////////////////////////////////

const TAB_BOTTOM = {
    HOME: 'TAB/HOME',
    COMMUNITY: 'TAB/COMMUNITY',
    NOTICE: 'TAB/NOTICE',
    MEMBERSHIP: 'TAB/MEMBERSHIP',
    MORE: 'TAB/MORE'
}

////////////////////////////////////////
// GLOBAL
////////////////////////////////////////

const GLOBAL = {
    ALERT: 'GLOBAL/ALERT',
}

////////////////////////////////////////
export default {
    SCREEN,
    SCREEN_ACTIVITY,
    STACK_LOGIN,
    STACK_HOME,
    STACK_COMMUNITY,
    STACK_NOTICE,
    STACK_MEMBERSHIP,
    STACK_MORE,
    TAB_BOTTOM,
    GLOBAL,
};
