export const getAlphabet = () => {
    return {
        A: [{id:'1', iso: 'AF', name: 'Afghanistan', code: '+93'},
            {id:'2', iso: 'AX', name: 'Aland Islands', code: '+358'},
            {id:'3', iso: 'AL', name: 'Albania', code: '+355'},
            {id:'4', iso: 'DZ', name: 'Algeria', code: '+213'},
            {id:'5', iso: 'AS', name: 'AmericanSamoa', code: '+1684'},
            {id:'6', iso: 'AD', name: 'Andorra', code: '+376'},
            {id:'7', iso: 'AO', name: 'Angola', code: '+244'},
            {id:'8', iso: 'AI', name: 'Anguilla', code: '+1264'},
            {id:'9', iso: 'AQ', name: 'Antarctica', code: '+672'},
            {id:'10', iso: 'AG', name: 'Antigua and Barbuda', code: '+1268'},
            {id:'11', iso: 'AR', name: 'Argentina', code: '+54'},
            {id:'12', iso: 'AM', name: 'Armenia', code: '+374'},
            {id:'13', iso: 'AW', name: 'Aruba', code: '+297'},
            {id:'14', iso: 'AU', name: 'Australia', code: '+61'},
            {id:'15', iso: 'AT', name: 'Austria', code: '+43'},
            {id:'16', iso: 'AZ', name: 'Azerbaijan', code: '+994'}],
        B: [{id:'17', iso: 'BS', name: 'Bahamas', code: '+1242'},
            {id:'18', iso: 'BH', name: 'Bahrain', code: '+973'},
            {id:'19', iso: 'BD', name: 'Bangladesh', code: '+880'},
            {id:'20', iso: 'BB', name: 'Barbados', code: '+1246'},
            {id:'21', iso: 'BY', name: 'Belarus', code: '+375'},
            {id:'22', iso: 'BE', name: 'Belgium', code: '+32'},
            {id:'23', iso: 'BZ', name: 'Belize', code: '+501'},
            {id:'24', iso: 'BJ', name: 'Benin', code: '+229'},
            {id:'25', iso: 'BM', name: 'Bermuda', code: '+1441'},
            {id:'26', iso: 'BT', name: 'Bhutan', code: '+975'},
            {id:'27', iso: 'BO', name: 'Bolivia, Plurinational State of', code: '+591'},
            {id:'28', iso: 'BA', name: 'Bosnia and Herzegovina', code: '+387'},
            {id:'29', iso: 'BW', name: 'Botswana', code: '+267'},
            {id:'30', iso: 'BR', name: 'Brazil', code: '+55'},
            {id:'31', iso: 'IO', name: 'British Indian Ocean Territory', code: '+246'},
            {id:'32', iso: 'BN', name: 'Brunei Darussalam', code: '+673'},
            {id:'33', iso: 'BG', name: 'Bulgaria', code: '+359'},
            {id:'34', iso: 'BF', name: 'Burkina Faso', code: '+226'},
            {id:'35', iso: 'BI', name: 'Burundi', code: '+257'}],
        C: [{id:'36', iso: 'KH', name: 'Cambodia', code: '+855'},
            {id:'37', iso: 'CM', name: 'Cameroon', code: '+237'},
            {id:'38', iso: 'CA', name: 'Canada', code: '+1'},
            {id:'39', iso: 'CV', name: 'Cape Verde', code: '+238'},
            {id:'40', iso: 'KY', name: 'Cayman Islands', code: '+ 345'},
            {id:'41', iso: 'CF', name: 'Central African Republic', code: '+236'},
            {id:'42', iso: 'TD', name: 'Chad', code: '+235'},
            {id:'43', iso: 'CL', name: 'Chile', code: '+56'},
            {id:'44', iso: 'CN', name: 'China', code: '+86'},
            {id:'45', iso: 'CX', name: 'Christmas Island', code: '+61'},
            {id:'46', iso: 'CC', name: 'Cocos (Keeling) Islands', code: '+61'},
            {id:'47', iso: 'CO', name: 'Colombia', code: '+57'},
            {id:'48', iso: 'KM', name: 'Comoros', code: '+269'},
            {id:'49', iso: 'CG', name: 'Congo', code: '+242'},
            {id:'50', iso: 'CD', name: 'Congo, The Democratic Republic of the Congo', code: '+243'},
            {id:'51', iso: 'CK', name: 'Cook Islands', code: '+682'},
            {id:'52', iso: 'CR', name: 'Costa Rica', code: '+506'},
            {id:'53', iso: 'CI', name: 'Cote d\'Ivoire', code: '+225'},
            {id:'54', iso: 'HR', name: 'Croatia', code: '+385'},
            {id:'55', iso: 'CU', name: 'Cuba', code: '+53'},
            {id:'56', iso: 'CY', name: 'Cyprus', code: '+357'},
            {id:'57', iso: 'CZ', name: 'Czech Republic', code: '+420'}],
        D: [{id:'58', iso: 'DK', name: 'Denmark', code: '+45'},
            {id:'59', iso: 'DJ', name: 'Djibouti', code: '+253'},
            {id:'60', iso: 'DM', name: 'Dominica', code: '+1767'},
            {id:'61', iso: 'DO', name: 'Dominican Republic', code: '+1849'}],
        E: [{id:'62', iso: 'EC', name: 'Ecuador', code: '+593'},
            {id:'63', iso: 'EG', name: 'Egypt', code: '+20'},
            {id:'64', iso: 'SV', name: 'El Salvador', code: '+503'},
            {id:'65', iso: 'GQ', name: 'Equatorial Guinea', code: '+240'},
            {id:'66', iso: 'ER', name: 'Eritrea', code: '+291'},
            {id:'67', iso: 'EE', name: 'Estonia', code: '+372'},
            {id:'68', iso: 'ET', name: 'Ethiopia', code: '+251'}],
        F: [{id:'69', iso: 'FK', name: 'Falkland Islands (Malvinas)', code: '+500'},
            {id:'70', iso: 'FO', name: 'Faroe Islands', code: '+298'},
            {id:'71', iso: 'FJ', name: 'Fiji', code: '+679'},
            {id:'72', iso: 'FI', name: 'Finland', code: '+358'},
            {id:'73', iso: 'FR', name: 'France', code: '+33'},
            {id:'74', iso: 'GF', name: 'French Guiana', code: '+594'},
            {id:'75', iso: 'PF', name: 'French Polynesia', code: '+689'}],
        G: [{id:'76', iso: 'GA', name: 'Gabon', code: '+241'},
            {id:'77', iso: 'GM', name: 'Gambia', code: '+220'},
            {id:'78', iso: 'GE', name: 'Georgia', code: '+995'},
            {id:'79', iso: 'DE', name: 'Germany', code: '+49'},
            {id:'80', iso: 'GH', name: 'Ghana', code: '+233'},
            {id:'81', iso: 'GI', name: 'Gibraltar', code: '+350'},
            {id:'82', iso: 'GR', name: 'Greece', code: '+30'},
            {id:'83', iso: 'GL', name: 'Greenland', code: '+299'},
            {id:'84', iso: 'GD', name: 'Grenada', code: '+1473'},
            {id:'85', iso: 'GP', name: 'Guadeloupe', code: '+590'},
            {id:'86', iso: 'GU', name: 'Guam', code: '+1671'},
            {id:'87', iso: 'GT', name: 'Guatemala', code: '+502'},
            {id:'88', iso: 'GG', name: 'Guernsey', code: '+44'},
            {id:'89', iso: 'GN', name: 'Guinea', code: '+224'},
            {id:'90', iso: 'GW', name: 'Guinea-Bissau', code: '+245'},
            {id:'91', iso: 'GY', name: 'Guyana', code: '+595'}],
        H: [{id:'92', iso: 'HT', name: 'Haiti', code: '+509'},
            {id:'93', iso: 'VA', name: 'Holy See (Vatican City State)', code: '+379'},
            {id:'94', iso: 'HN', name: 'Honduras', code: '+504'},
            {id:'95', iso: 'HK', name: 'Hong Kong', code: '+852'},
            {id:'96', iso: 'HU', name: 'Hungary', code: '+36'}],
        I: [{id:'97', iso: 'IS', name: 'Iceland', code: '+354'},
            {id:'98', iso: 'IN', name: 'India', code: '+91'},
            {id:'99', iso: 'ID', name: 'Indonesia', code: '+62'},
            {id:'100', iso: 'IR', name: 'Iran, Islamic Republic of Persian Gulf', code: '+98'},
            {id:'101', iso: 'IQ', name: 'Iraq', code: '+964'},
            {id:'102', iso: 'IE', name: 'Ireland', code: '+353'},
            {id:'103', iso: 'IM', name: 'Isle of Man', code: '+44'},
            {id:'104', iso: 'IL', name: 'Israel', code: '+972'},
            {id:'105', iso: 'IT', name: 'Italy', code: '+39'}],
        J: [{id:'106', iso: 'JM', name: 'Jamaica', code: '+1876'},
            {id:'107', iso: 'JP', name: 'Japan', code: '+81'},
            {id:'108', iso: 'JE', name: 'Jersey', code: '+44'},
            {id:'109', iso: 'JO', name: 'Jordan', code: '+962'}],
        K: [{id:'110', iso: 'KZ', name: 'Kazakhstan', code: '+77'},
            {id:'111', iso: 'KE', name: 'Kenya', code: '+254'},
            {id:'112', iso: 'KI', name: 'Kiribati', code: '+686'},
            {id:'113', iso: 'KP', name: 'Korea, Democratic People\'s Republic of Korea', code: '+850'},
            {id:'114', iso: 'KR', name: 'Korea, Republic of Korea', code: '+82'},
            {id:'115', iso: 'KW', name: 'Kuwait', code: '+965'},
            {id:'116', iso: 'KG', name: 'Kyrgyzstan', code: '+996'}],
        L: [{id:'117', iso: 'LA', name: 'Laos', code: '+856'},
            {id:'118', iso: 'LV', name: 'Latvia', code: '+371'},
            {id:'119', iso: 'LB', name: 'Lebanon', code: '+961'},
            {id:'120', iso: 'LS', name: 'Lesotho', code: '+266'},
            {id:'121', iso: 'LR', name: 'Liberia', code: '+231'},
            {id:'122', iso: 'LY', name: 'Libyan Arab Jamahiriya', code: '+218'},
            {id:'123', iso: 'LI', name: 'Liechtenstein', code: '+423'},
            {id:'124', iso: 'LT', name: 'Lithuania', code: '+370'},
            {id:'125', iso: 'LU', name: 'Luxembourg', code: '+352'}],
        M: [{id:'126', iso: 'MO', name: 'Macao', code: '+853'},
            {id:'127', iso: 'MK', name: 'Macedonia', code: '+389'},
            {id:'128', iso: 'MG', name: 'Madagascar', code: '+261'},
            {id:'129', iso: 'MW', name: 'Malawi', code: '+265'},
            {id:'130', iso: 'MY', name: 'Malaysia', code: '+60'},
            {id:'131', iso: 'MV', name: 'Maldives', code: '+960'},
            {id:'132', iso: 'ML', name: 'Mali', code: '+223'},
            {id:'133', iso: 'MT', name: 'Malta', code: '+356'},
            {id:'134', iso: 'MH', name: 'Marshall Islands', code: '+692'},
            {id:'135', iso: 'MQ', name: 'Martinique', code: '+596'},
            {id:'136', iso: 'MR', name: 'Mauritania', code: '+222'},
            {id:'137', iso: 'MU', name: 'Mauritius', code: '+230'},
            {id:'138', iso: 'YT', name: 'Mayotte', code: '+262'},
            {id:'139', iso: 'MX', name: 'Mexico', code: '+52'},
            {id:'140', iso: 'FM', name: 'Micronesia, Federated States of Micronesia', code: '+691'},
            {id:'141', iso: 'MD', name: 'Moldova', code: '+373'},
            {id:'142', iso: 'MC', name: 'Monaco', code: '+377'},
            {id:'143', iso: 'MN', name: 'Mongolia', code: '+976'},
            {id:'144', iso: 'ME', name: 'Montenegro', code: '+382'},
            {id:'145', iso: 'MS', name: 'Montserrat', code: '+1664'},
            {id:'146', iso: 'MA', name: 'Morocco', code: '+212'},
            {id:'147', iso: 'MZ', name: 'Mozambique', code: '+258'},
            {id:'148', iso: 'MM', name: 'Myanmar', code: '+95'}],
        N: [{id:'149', iso: 'NA', name: 'Namibia', code: '+264'},
            {id:'150', iso: 'NR', name: 'Nauru', code: '+674'},
            {id:'151', iso: 'NP', name: 'Nepal', code: '+977'},
            {id:'152', iso: 'NL', name: 'Netherlands', code: '+31'},
            {id:'153', iso: 'AN', name: 'Netherlands Antilles', code: '+599'},
            {id:'154', iso: 'NC', name: 'New Caledonia', code: '+687'},
            {id:'155', iso: 'NZ', name: 'New Zealand', code: '+64'},
            {id:'156', iso: 'NI', name: 'Nicaragua', code: '+505'},
            {id:'157', iso: 'NE', name: 'Niger', code: '+227'},
            {id:'158', iso: 'NG', name: 'Nigeria', code: '+234'},
            {id:'159', iso: 'NU', name: 'Niue', code: '+683'},
            {id:'160', iso: 'NF', name: 'Norfolk Island', code: '+672'},
            {id:'161', iso: 'MP', name: 'Northern Mariana Islands', code: '+1670'},
            {id:'162', iso: 'NO', name: 'Norway', code: '+47'}],
        O: [{id:'163', iso: 'OM', name: 'Oman', code: '+968'}],
        P: [{id:'164', iso: 'PK', name: 'Pakistan', code: '+92'},
            {id:'165', iso: 'PW', name: 'Palau', code: '+680'},
            {id:'166', iso: 'PS', name: 'Palestinian Territory, Occupied', code: '+970'},
            {id:'167', iso: 'PA', name: 'Panama', code: '+507'},
            {id:'168', iso: 'PG', name: 'Papua New Guinea', code: '+675'},
            {id:'169', iso: 'PY', name: 'Paraguay', code: '+595'},
            {id:'170', iso: 'PE', name: 'Peru', code: '+51'},
            {id:'171', iso: 'PH', name: 'Philippines', code: '+63'},
            {id:'172', iso: 'PN', name: 'Pitcairn', code: '+872'},
            {id:'173', iso: 'PL', name: 'Poland', code: '+48'},
            {id:'174', iso: 'PT', name: 'Portugal', code: '+351'},
            {id:'175', iso: 'PR', name: 'Puerto Rico', code: '+1939'}],
        Q: [{id:'176', iso: 'QA', name: 'Qatar', code: '+974'}],
        R: [{id:'177', iso: 'RO', name: 'Romania', code: '+40'},
            {id:'178', iso: 'RU', name: 'Russia', code: '+7'},
            {id:'179', iso: 'RW', name: 'Rwanda', code: '+250'},
            {id:'180', iso: 'RE', name: 'Reunion', code: '+262'}],
        S: [{id:'181', iso: 'BL', name: 'Saint Barthelemy', code: '+590'},
            {id:'182', iso: 'SH', name: 'Saint Helena, Ascension and Tristan Da Cunha', code: '+290'},
            {id:'183', iso: 'KN', name: 'Saint Kitts and Nevis', code: '+1869'},
            {id:'184', iso: 'LC', name: 'Saint Lucia', code: '+1758'},
            {id:'185', iso: 'MF', name: 'Saint Martin', code: '+590'},
            {id:'186', iso: 'PM', name: 'Saint Pierre and Miquelon', code: '+508'},
            {id:'187', iso: 'VC', name: 'Saint Vincent and the Grenadines', code: '+1784'},
            {id:'188', iso: 'WS', name: 'Samoa', code: '+685'},
            {id:'189', iso: 'SM', name: 'San Marino', code: '+378'},
            {id:'190', iso: 'ST', name: 'Sao Tome and Principe', code: '+239'},
            {id:'191', iso: 'SA', name: 'Saudi Arabia', code: '+966'},
            {id:'192', iso: 'SN', name: 'Senegal', code: '+221'},
            {id:'193', iso: 'RS', name: 'Serbia', code: '+381'},
            {id:'194', iso: 'SC', name: 'Seychelles', code: '+248'},
            {id:'195', iso: 'SL', name: 'Sierra Leone', code: '+232'},
            {id:'196', iso: 'SG', name: 'Singapore', code: '+65'},
            {id:'197', iso: 'SK', name: 'Slovakia', code: '+421'},
            {id:'198', iso: 'SI', name: 'Slovenia', code: '+386'},
            {id:'199', iso: 'SB', name: 'Solomon Islands', code: '+677'},
            {id:'200', iso: 'SO', name: 'Somalia', code: '+252'},
            {id:'201', iso: 'ZA', name: 'South Africa', code: '+27'},
            {id:'202', iso: 'SS', name: 'South Sudan', code: '+211'},
            {id:'203', iso: 'GS', name: 'South Georgia and the South Sandwich Islands', code: '+500'},
            {id:'204', iso: 'ES', name: 'Spain', code: '+34'},
            {id:'205', iso: 'LK', name: 'Sri Lanka', code: '+94'},
            {id:'206', iso: 'SD', name: 'Sudan', code: '+249'},
            {id:'207', iso: 'SR', name: 'Suriname', code: '+597'},
            {id:'208', iso: 'SJ', name: 'Svalbard and Jan Mayen', code: '+47'},
            {id:'209', iso: 'SZ', name: 'Swaziland', code: '+268'},
            {id:'210', iso: 'SE', name: 'Sweden', code: '+46'},
            {id:'211', iso: 'CH', name: 'Switzerland', code: '+41'},
            {id:'212', iso: 'SY', name: 'Syrian Arab Republic', code: '+963'}],
        T: [{id:'213', iso: 'TW', name: 'Taiwan', code: '+886'},
            {id:'214', iso: 'TJ', name: 'Tajikistan', code: '+992'},
            {id:'215', iso: 'TZ', name: 'Tanzania, United Republic of Tanzania', code: '+255'},
            {id:'216', iso: 'TH', name: 'Thailand', code: '+66'},
            {id:'217', iso: 'TL', name: 'Timor-Leste', code: '+670'},
            {id:'218', iso: 'TG', name: 'Togo', code: '+228'},
            {id:'219', iso: 'TK', name: 'Tokelau', code: '+690'},
            {id:'220', iso: 'TO', name: 'Tonga', code: '+676'},
            {id:'221', iso: 'TT', name: 'Trinidad and Tobago', code: '+1868'},
            {id:'222', iso: 'TN', name: 'Tunisia', code: '+216'},
            {id:'223', iso: 'TR', name: 'Turkey', code: '+90'},
            {id:'224', iso: 'TM', name: 'Turkmenistan', code: '+993'},
            {id:'225', iso: 'TC', name: 'Turks and Caicos Islands', code: '+1649'},
            {id:'226', iso: 'TV', name: 'Tuvalu', code: '+688'}],
        U: [{id:'227', iso: 'UG', name: 'Uganda', code: '+256'},
            {id:'228', iso: 'UA', name: 'Ukraine', code: '+380'},
            {id:'229', iso: 'AE', name: 'United Arab Emirates', code: '+971'},
            {id:'230', iso: 'GB', name: 'United Kingdom', code: '+44'},
            {id:'231', iso: 'US', name: 'USA, United States of America', code: '+1'},
            {id:'232', iso: 'UY', name: 'Uruguay', code: '+598'},
            {id:'233', iso: 'UZ', name: 'Uzbekistan', code: '+998'}],
        V: [{id:'234', iso: 'VU', name: 'Vanuatu', code: '+678'},
            {id:'235', iso: 'VE', name: 'Venezuela, Bolivarian Republic of Venezuela', code: '+58'},
            {id:'236', iso: 'VN', name: 'Vietnam', code: '+84'},
            {id:'237', iso: 'VG', name: 'Virgin Islands, British', code: '+1284'},
            {id:'238', iso: 'VI', name: 'Virgin Islands, U.S.', code: '+1340'}],
        W: [{id:'239', iso: 'WF', name: 'Wallis and Futuna', code: '+681'}],
        Y: [{id:'240', iso: 'YE', name: 'Yemen', code: '+967'}],
        Z: [{id:'241', iso: 'ZM', name: 'Zambia', code: '+260'},
            {id:'242', iso: 'ZW', name: 'Zimbabwe', code: '+263'}]
    }
}